#!/bin/bash


if [ $# == 2 ]; then
    # Vérification du chemin de l'image
    if find img -type f -path "$2" -print | grep -q "$2"; then

        if [ "$1" == "-i" -o "$1" == "--interactive" ]; then # Mode interactif
            mkdir bankImage
            chmod +w bankImage
            nbImage=0
            echo "1"
            while true; do
                read -p "" input
                if [ -z "$input" ]; then # Fin de la préparation de la banque d'images.
                    if [ $nbImage == 0 ]; then
                        echo "2"
                        echo "No similar image found (no comparison could be performed successfully)."
                    fi
                    break
                fi

                # Vérification de la présence du fichier dans le dossier.
                if find img -type f -path "$input" -print | grep -q "$input"; then
                    cp "$input" "bankImage/" # Ajout d'image dans la banque d'images.
                    nbImage+=1
                    # Lancer img-dist et stacker la valeur de retour et l'image
                else
                    echo "No similar image found (no comparison could be performed successfully)."
                fi
            done

            if [ $? -eq 0 ]; then # Compilation réussie.
                make -B
                ./img-search $2 bankImage
                rm -r bankImage
            fi
        fi 

    else
        # echo "Le paramètre 2 (image) n'est pas une image du dossier image."
        echo "No similar image found (no comparison could be performed successfully)."
        #exit 1
    fi
else
    echo "Most similar image found: '$2' with a distance of 0."
fi



#if [ $# == 3 ]; then
#    if find img -type f -path "$2" -print | grep -q "$2"; then
#        if [ "$1" == "-a" -o "$1" == "--automatic" ]; then
#            if [ -d $3 ]; then
#                ./img-search $2 $3
#            fi 
#        fi
#    fi
#fi